name: Connect to VPN
run-name: Connect to VPN
on: [push]

env:
  NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
  NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}

jobs:
  deploy-nomad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- run: |
      #    echo ${{ vars.TS_OAUTH_CLIENT_ID }}
      #    echo ${{ vars.TS_OAUTH_SECRET }}

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
          #tags: tag:ci

      - name: Setup Nomad
        uses: lucasmelin/setup-nomad@v2.0.0
      - name: Connect to Nomad
        run: nomad status
